# Generated by Django 4.2.6 on 2023-12-14 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('salesman_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('commission', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_no', models.IntegerField(primary_key=True, serialize=False)),
                ('cus_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('email', models.EmailField(default='india@gmail.com', max_length=254)),
                ('salesman_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.salesman')),
            ],
        ),
    ]
